from fastapi import FastAPI, File, UploadFile, Form
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse, JSONResponse
from typing import List, Tuple
import io
import zipfile
from docx import Document

from utilities.executor import process_plan
from utilities.planner import plan_from_llm

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)



@app.post("/process")
async def process_files(
    files: List[UploadFile] = File(...),
    user_prompt: str = Form(...)
):
    print(f"🔔 API called with user_prompt: {user_prompt}")
    print(f"🔔 Received {len(files)} file(s)")

    # Read and prepare files into memory
    memory_files = {}
    for file in files:
        memory_files[file.filename] = io.BytesIO(await file.read())

    # Generate plan from Gemini
    plan = await plan_from_llm(user_prompt)
    print(f"💡 Plan generated by LLM: {plan}")

    # Run plan on each file
    processed_outputs, results = process_plan(plan, memory_files)
    print(f"✅ Process results: {results}")

    if not processed_outputs:
        return JSONResponse(status_code=500, content={"error": "No files processed successfully."})

    # If only one file was processed, return it directly
    if len(processed_outputs) == 1:
        filename, buffer = processed_outputs[0]
        buffer.seek(0)
        return StreamingResponse(buffer, media_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document", headers={"Content-Disposition": f"attachment; filename={filename}"})

    # Multiple files – zip them
    zip_buffer = io.BytesIO()
    with zipfile.ZipFile(zip_buffer, "w") as zip_file:
        for filename, buffer in processed_outputs:
            if buffer:
                buffer.seek(0)
                zip_file.writestr(filename, buffer.read())
    zip_buffer.seek(0)

    return StreamingResponse(zip_buffer, media_type="application/zip", headers={"Content-Disposition": "attachment; filename=processed_files.zip"})
