from fastapi import FastAPI, UploadFile, Form
from fastapi.responses import FileResponse
from fastapi.middleware.cors import CORSMiddleware
import shutil
import pathlib
import os

from process_plan import plan_from_llm, process_plan  # reuse your logic!

app = FastAPI()

# Enable CORS for frontend access
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:3000"],  # React dev server origin
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.post("/process")
async def process_files(user_prompt: str = Form(...), files: list[UploadFile] = []):
    print("🔔 API called with user_prompt:", user_prompt)
    print(f"🔔 Received {len(files)} file(s)")

    # Temporary folders for this run:
    src_dir = pathlib.Path("./web_input")
    out_dir = pathlib.Path("./web_output")
    src_dir.mkdir(exist_ok=True)
    out_dir.mkdir(exist_ok=True)

    # Cleanup old files (optional but useful for debugging)
    for f in src_dir.glob("*"):
        f.unlink()
    for f in out_dir.glob("*"):
        f.unlink()

    # Save uploaded files
    for f in files:
        file_path = src_dir / f.filename
        print(f"💾 Saving uploaded file to {file_path}")
        with open(file_path, "wb") as buffer:
            shutil.copyfileobj(f.file, buffer)

    # Generate plan from LLM
    plan = plan_from_llm(user_prompt)
    print("💡 Plan generated by LLM:", plan)

    if not plan:
        print("⚠️ Empty plan received from LLM!")
        return {"status": "error", "message": "LLM did not return a valid plan."}

    # Process plan
    print(f"⚙️ Processing files in {src_dir} → {out_dir}")
    results = process_plan(plan, src_dir, out_dir)
    print("✅ Process results:", results)

    # Check output
    output_file = out_dir / "merged_files.docx"
    if output_file.exists():
        print(f"✅ Returning merged output: {output_file}")
        return FileResponse(output_file, filename="processed.docx")

    processed_files = list(out_dir.glob("*.docx"))
    if processed_files:
        print(f"✅ Returning first processed file: {processed_files[0]}")
        return FileResponse(processed_files[0], filename="processed.docx")

    print("❌ No output files produced")
    return {"status": "error", "message": "No output files produced"}

