# main.py

from fastapi import FastAPI, UploadFile, File, Form
from fastapi.responses import StreamingResponse, JSONResponse
from fastapi.middleware.cors import CORSMiddleware
from typing import List
from io import BytesIO
import zipfile

from get_plan_from_gemini import plan_from_llm
from process_plan import process_plan

app = FastAPI()

# Allow CORS for local frontend
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:3000"],  # Update for production
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.post("/process")
async def process_files(
    files: List[UploadFile] = File(...),
    user_prompt: str = Form(...)
):
    print(f"🔔 API called with user_prompt: {user_prompt}")
    print(f"🔔 Received {len(files)} file(s)")

    try:
        plan = await plan_from_llm(user_prompt)
        print(f"💡 Plan generated by LLM: {plan}")
    except Exception as e:
        return JSONResponse(status_code=500, content={"error": f"LLM error: {e}"})

    all_outputs, results = process_plan(plan, files)

    if not all_outputs:
        return JSONResponse(status_code=500, content={"error": "Processing failed", "results": results})

    if len(all_outputs) == 1:
        filename, buffer = all_outputs[0]
        buffer.seek(0)
        return StreamingResponse(
            buffer,
            media_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            headers={"Content-Disposition": f"attachment; filename={filename}"}
        )
    else:
        zip_buf = BytesIO()
        with zipfile.ZipFile(zip_buf, "w", zipfile.ZIP_DEFLATED) as zipf:
            for filename, buf in all_outputs:
                buf.seek(0)
                zipf.writestr(filename, buf.read())
        zip_buf.seek(0)
        return StreamingResponse(
            zip_buf,
            media_type="application/zip",
            headers={"Content-Disposition": "attachment; filename=processed_files.zip"}
        )
